vilebot/src/com/oldterns/vilebot/handlers/user/AnswerQuestion.java, vilebot/src/com/oldterns/vilebot/handlers/user/Help.java
!tellme <query> can be used to query wolfram. Vilebot will send a wolfram api query and reply with the first plaintext response from wolfram (or can't find answer) otherwise.
=> !tellme command/wolfram integration

vilebot/src/com/oldterns/vilebot/handlers/user/Jokes.java
The joke was bad.
Signed-off-by: Ian Stewart-Binks <istewart@redhat.com>
=> Updated joke

.gitignore, vilebot/src/com/oldterns/vilebot/handlers/user/AnswerQuestion.java, vilebot/src/com/oldterns/vilebot/handlers/user/GetInfoOn.java
Basically just merging in my master to sync up oldterns/VileBot with my fork. All future feature additions will be given their own branches from here on out.
=> !infoon command and some !tellme cleanups

vilebot/src/com/oldterns/vilebot/handlers/user/AnswerQuestion.java, vilebot/src/com/oldterns/vilebot/handlers/user/GetInfoOn.java
VileBot will no longer process an unencoded url. Bit of code duplication removal in the infoon/infun regex processing.
=> Tellme and URL encoding refactor

vilebot/src/com/oldterns/vilebot/handlers/user/AnswerQuestion.java, vilebot/src/com/oldterns/vilebot/handlers/user/GetInfoOn.java, vilebot/src/com/oldterns/vilebot/handlers/user/Ttc.java
Includes commits related to adding ttc alert handler.
=> TTC handler

vilebot/src/com/oldterns/vilebot/handlers/user/AnswerQuestion.java, vilebot/src/com/oldterns/vilebot/handlers/user/Markov.java, vilebot/src/com/oldterns/vilebot/handlers/user/Ttc.java
Mangle nicks generated from the !speak command so users are not mentioned. Limit the response size for tellme so people cannot channel flood be requesting many thousand digits of pi...
=> Toning some things down.

vilebot/src/com/oldterns/vilebot/handlers/user/KarmaRoll.java
Rolls can now be any size, as long as the user has enough karma to
match.
=> Removing hard limit on karma rolls

vilebot/src/com/oldterns/vilebot/handlers/user/KarmaRoll.java
=> Only roll game initiator can cancel game

vilebot/src/com/oldterns/vilebot/handlers/user/KarmaRoll.java
=> No private rolling

vilebot/src/com/oldterns/vilebot/db/ChurchDB.java, vilebot/src/com/oldterns/vilebot/handlers/user/Church.java, vilebot/src/com/oldterns/vilebot/handlers/user/Help.java, vilebot/src/com/oldterns/vilebot/handlers/user/Karma.java, vilebot/src/com/oldterns/vilebot/handlers/user/Markov.java, vilebot/src/com/oldterns/vilebot/handlers/user/QuotesAndFacts.java, vilebot/src/com/oldterns/vilebot/util/Zalgo.java
Add initial Church of VileBot functionality, including:
- donate (!donate)
- viewing total donations (!churchtotal)
- see top 4 donors and titles (!topdonors)
- set your title if you're one of the top 4 donors (!settitle <noun>)
- have VileBot speak in Zalgo instead of normal (!gospel)
=> Church Commands Version 1

vilebot/src/com/oldterns/vilebot/handlers/user/Help.java, vilebot/src/com/oldterns/vilebot/handlers/user/QuotesAndFacts.java
Add !quotedump and !factdump <name> which will privately
message the invoker all quotes/facts that <name> has.
=> Add fact/quote dumping

vilebot/src/com/oldterns/vilebot/util/Zalgo.java
Simplify Zalgo algorithm:
For each character in input message, insert a diacritic if the random
float generated is less than the Z_RATE.
=> Zalgo updates

vilebot/src/com/oldterns/vilebot/db/ChurchDB.java, vilebot/src/com/oldterns/vilebot/handlers/user/Church.java, vilebot/src/com/oldterns/vilebot/handlers/user/Help.java
Add ability to start an inquisition vote against a church member
with !inquisit. This vote can only be invoked and passed by a
top 4 member.
=> Add inquisit command

vilebot/src/com/oldterns/vilebot/handlers/user/Jokes.java, vilebot/src/com/oldterns/vilebot/handlers/user/Omgword.java
Vilebot will spout out random jokes about containers if anything about containers is talked about
=> Fixed refactoring and included new container joke feature

README.md, vilebot/src/com/oldterns/vilebot/handlers/user/Jokes.java
Added some documentation about the use of the files folder for future developers. 
Added an additional joke in replacement of some others.
=> Documentation about our files folder (wordlist.txt), fixed jokes

vilebot/src/main/java/com/oldterns/vilebot/handlers/user/Jaziz.java
=> !jaziz now works with punctuation

vilebot/src/main/java/com/oldterns/vilebot/handlers/user/Countdown.java, vilebot/src/main/java/com/oldterns/vilebot/handlers/user/Help.java
mainly aesthetics, but also includes !countdownrules
=> Some additional fixes for Countdown

vilebot/src/main/java/com/oldterns/vilebot/handlers/user/QuotesAndFacts.java, vilebot/src/main/java/com/oldterns/vilebot/util/StringUtil.java, vilebot/src/test/java/vilebot/util/StringUtilTest.java
The lack of capitalization when the bot talks triggers me
=> Added capitalization and unit tests

vilebot/cfg/vilebot.conf.example, vilebot/src/main/java/com/oldterns/vilebot/handlers/user/Help.java, vilebot/src/main/java/com/oldterns/vilebot/handlers/user/RockPaperScissors.java
Can someone please test this? For some reason my handler was never activated (Countdown was also not activated on my machine, but Jeopardy and OMGWord were).
=> Added Rock Paper Scissors game

vilebot/files/fortunelist.txt, vilebot/src/main/java/com/oldterns/vilebot/handlers/user/Church.java
Found this spelling mistake in the Church.java file and the inspiration file.
=> Fix spelling mistake of decision

vilebot/files/fortunelist.txt, vilebot/src/main/java/com/oldterns/vilebot/handlers/user/Church.java
Reverts oldterns/VileBot#89
wait for tests to pass.
=> Revert "Fix spelling mistake of decision"

.travis.yml, vilebot/src/main/java/com/oldterns/vilebot/handlers/user/Trivia.java, vilebot/src/test/java/vilebot/handlers/user/TriviaTest.java
The bug breaking jeopardy was caused by invalidFlag always getting set (not sure why this was happening), so removing invalidFlag fixed the issue. Also added a check to prevent infinite recursion when question is constantly returned as being empty.
Fixes https://github.com/oldterns/VileBot/issues/94
=> Fixes bug causing Jeopardy to not work

vilebot/src/main/java/com/oldterns/vilebot/handlers/user/Help.java, vilebot/src/main/java/com/oldterns/vilebot/handlers/user/RemindMe.java, vilebot/src/test/java/vilebot/handlers/user/RemindMeTest.java
Some additions and fixes the the !remindme command. Incorporates some of @amisevsk comments.
=> Some fixes for remindme

vilebot/src/main/java/com/oldterns/vilebot/handlers/user/Karma.java
Similar to $nick++ and $nick-- but instead randomly decides between ++ and --. Currently the functionality can be replicated with !decide $nick++|$nick-- > !$nick$result, it leaves -+ as not doing anything if a neutral option is still wanted. No tests because for the life of me I could not get the redis database to start up for the tests so kept getting errors with testing adding/decreasing karma.
=> Add the ability to use +- to randomly up or down vote

vilebot/src/main/java/com/oldterns/vilebot/handlers/user/Help.java
Think this is what was needed to be added?
will double check in chat on Monday
=> Help: add entry for +-

vilebot/cfg/vilebot.conf.example, vilebot/pom.xml, vilebot/src/main/java/com/oldterns/vilebot/handlers/user/Markov.java, vilebot/src/main/java/com/oldterns/vilebot/handlers/user/QuotesAndFacts.java, vilebot/src/main/java/com/oldterns/vilebot/util/MangleNicks.java, vilebot/src/test/java/vilebot/util/MangleNicksTest.java
Addresses issue #102
Refactor mangleNicks method in Markov to a util class and use it in QuotesAndFacts to reverse any nicks
=> Reverse nicks in quotes/facts

vilebot/src/main/java/com/oldterns/vilebot/handlers/user/Fortune.java, vilebot/src/main/java/com/oldterns/vilebot/handlers/user/Inspiration.java, vilebot/src/main/java/com/oldterns/vilebot/handlers/user/Omgword.java, vilebot/src/main/java/com/oldterns/vilebot/handlers/user/QuotesAndFacts.java, vilebot/src/test/java/vilebot/util/MangleNicksTest.java
Fixes the following issue
Current output of "!quote jucook": koocuj once said, "Hmm namlas I don't think your PR works".
Expected output: jucook once said, "Hmm namlas I don't think your PR works".
=> dont reverse nick at beginning of quote/fact query

vilebot/src/main/java/com/oldterns/vilebot/handlers/user/Ascii.java, vilebot/src/main/java/com/oldterns/vilebot/util/LimitCommand.java, vilebot/src/test/java/vilebot/handlers/user/AsciiTest.java, vilebot/src/test/java/vilebot/util/LimitCommandTest.java
Initially setting the default values as 2 messages per 5 minutes
=> Create new LimitCommand utility to create limits on amount of times a VileBot command can be used per time period and add it to Ascii

vilebot/src/main/java/com/oldterns/vilebot/handlers/user/Countdown.java, vilebot/src/main/java/com/oldterns/vilebot/handlers/user/Omgword.java, vilebot/src/main/java/com/oldterns/vilebot/handlers/user/Trivia.java
replace messages with "\n" characters with list/array of messages
=> fix for Countdown, Trivia and Omgword for pircbotx changes

vilebot/src/main/java/com/oldterns/vilebot/util/BaseNick.java, vilebot/src/test/java/vilebot/util/BaseNickTest.java
=> fix BaseNick to correctly handle nicks with special chars

vilebot/src/main/java/com/oldterns/vilebot/handlers/user/FakeNews.java, vilebot/src/main/java/com/oldterns/vilebot/handlers/user/News.java, vilebot/src/main/java/com/oldterns/vilebot/util/NewsParser.java, vilebot/src/test/java/vilebot/handlers/user/FakeNewsTest.java, vilebot/src/test/java/vilebot/handlers/user/NewsTest.java
- Fix LimitCommand so that invalid news category input doesn't count as a use
- Improve invalid news category error message
=> Fix LimitCommand for printing headlines, fix help message

vilebot/src/main/java/com/oldterns/vilebot/db/ChurchDB.java, vilebot/src/main/java/com/oldterns/vilebot/handlers/user/Karma.java, vilebot/src/main/java/com/oldterns/vilebot/handlers/user/QuotesAndFacts.java
=> fix title display for church's 4th top donor

vilebot/src/main/java/com/oldterns/vilebot/handlers/user/QuotesAndFacts.java
quote/fact dumps will be password protected
=> add password to pastebin link

vilebot/pom.xml, vilebot/src/main/java/com/oldterns/vilebot/db/LogDB.java
=> add limit to log size

vilebot/cfg/vilebot.conf.example, vilebot/src/main/java/com/oldterns/vilebot/handlers/user/Countdown.java, vilebot/src/main/java/com/oldterns/vilebot/handlers/user/KarmaTransfer.java, vilebot/src/test/java/vilebot/handlers/user/CountdownTest.java
Fixes https://github.com/oldterns/VileBot/issues/132.
Minor formatting fixes and adds basic unit tests.
=> Fix Countdown game

vilebot/src/main/java/com/oldterns/vilebot/handlers/user/Church.java
Signed-off-by: David Thompson <davthomp@redhat.com>
=> Rewording a church message

vilebot/src/main/java/com/oldterns/vilebot/handlers/user/UserPing.java
Can be helpful if multiple people ping at once, or for testing if IRC client notifications are working properly.
Signed-off-by: David Thompson <davthomp@redhat.com>
=> !ping replies with nickname
